### ISSUE TITLE
Is it possible to vote but use a certain amount of an SPL Token on solana to vote. Instead of just Solana. 

### ISSUE THREAD

**Issue by juansebsol** [bfriel/crunchy-vs-smooth-v2#1]
Is it possible to vote but use a certain amount of an SPL Token on solana to vote. Instead of just Solana. 
I tried going over the github project but could not find where the payment token was specified or if it even was.

**Comment by bfriel** [comment]
Yes, but that's not what this app is doing. This app is simply 1 tx = 1 vote. It lets anyone vote and does not limit the amount of votes they can cast.

You must pay with SOL because these are real txs on the Solana network. The SOL is just the network fee to send the tx, nothing more.

If you are looking to learn how to implement an SPL-token weighted vote I would check out this repo https://github.com/TribecaHQ/tribeca
